- id: "1617007136486"
  alias: Dressroom window, air purifier plug
  description: ""
  use_blueprint:
    path: custom/contact_switch.yaml
    input:
      window_entity: binary_sensor.smartthings_dressroom_contact_contact
      switch_target: switch.dawon_dressroom_plug
      minimum_open_time: 12
- id: "1617276803759"
  alias: Bedroom window, air purifier
  description: ""
  use_blueprint:
    path: custom/contact_switch.yaml
    input:
      window_entity: binary_sensor.smartthings_bedroom_contact_contact
      minimum_open_time: 12
      switch_target: switch.anbang_gonggiceongjeonggi
- id: "1617276883183"
  alias: Bedroom window, humidifier
  description: ""
  use_blueprint:
    path: custom/contact_switch.yaml
    input:
      window_entity: binary_sensor.smartthings_bedroom_contact_contact
      switch_target: switch.dawon_bedroom_humidifier_plug
- id: "1617443911976"
  alias: Dish washer monitor
  description: ""
  use_blueprint:
    path: custom/power_monitor.yaml
    input:
      power_sensor: sensor.dawon_kitchen_dishwasher_plug_power
      starting_threshold: 2
      starting_hysteresis: 0.25
      finishing_threshold: 3
      finishing_hysteresis: 5
      starting_actions:
        - service: notify.notify_telegram
          data:
            message: "식기 세척을 시작합니다."
        - service: input_boolean.turn_on
          target:
            entity_id: input_boolean.dish_washer_state
        - condition: state
          entity_id: alarm_control_panel.home_monitoring
          state: "disarmed"
        - service: notify.galaxy_cloud_speak
          data:
            message: "식기 세척을 시작합니다."
      ending_actions:
        - service: notify.notify_telegram
          data:
            message: "식기 세척이 완료되었습니다."
        - service: input_boolean.turn_off
          target:
            entity_id: input_boolean.dish_washer_state
        - condition: state
          entity_id: alarm_control_panel.home_monitoring
          state: "disarmed"
        - service: notify.galaxy_cloud_speak
          data:
            message: "식기 세척이 완료되었습니다."
- id: "1617444167235"
  alias: Food waste processor monitor
  description: ""
  use_blueprint:
    path: custom/power_monitor.yaml
    input:
      power_sensor: sensor.dawon_kitchen_foodwaste_plug_power
      starting_threshold: 30
      starting_hysteresis: 1
      finishing_threshold: 15
      finishing_hysteresis: 10
      starting_actions:
        - service: notify.notify_telegram
          data:
            message: "음식물 쓰레기 처리를 시작합니다."
        - service: input_boolean.turn_on
          target:
            entity_id: input_boolean.food_waste_machine_state
        - service: switch.turn_on
          target:
            entity_id: switch.dawon_kitchen_fan_plug
        - condition: state
          entity_id: alarm_control_panel.home_monitoring
          state: "disarmed"
        - service: notify.galaxy_cloud_speak
          data:
            message: "음식물 쓰레기 처리를 시작합니다."
      ending_actions:
        - service: notify.notify_telegram
          data:
            message: "음식물 쓰레기 처리가 완료되었습니다."
        - service: input_boolean.turn_off
          target:
            entity_id: input_boolean.food_waste_machine_state
        - service: switch.turn_off
          target:
            entity_id: switch.dawon_kitchen_fan_plug
        - condition: state
          entity_id: alarm_control_panel.home_monitoring
          state: "disarmed"
        - service: notify.galaxy_cloud_speak
          data:
            message: "음식물 쓰레기 처리가 완료되었습니다."
