# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  name: !secret ha_name
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: !secret unit_system
  time_zone: !secret time_zone
  external_url: !secret external_url
  internal_url: !secret internal_url
  packages: !include_dir_merge_named packages/

http:
  ip_ban_enabled: true
  login_attempts_threshold: 3
  use_x_forwarded_for: true
  trusted_proxies:
    - !secret docker_ips
    - !secret subnet_ips

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
# themes
frontend:
  # themes: ios-dark-mode, light-soft-ui
  themes: !include_dir_merge_named themes
recorder: !include recorder.yaml
history: !include history.yaml
logbook: !include logbook.yaml

# manual home alarm: https://www.home-assistant.io/integrations/manual
alarm_control_panel:
  - platform: manual
    name: home_monitoring

# yaml lovelace dashboard
lovelace:
  mode: yaml
  resources:
    - url: /local/community/vertical-stack-in-card/vertical-stack-in-card.js
      type: module
    - url: /local/community/lovelace-card-mod/card-mod.js
      type: module
    - url: /local/community/button-card/button-card.js
      type: module
    - url: /local/community/zigbee2mqtt-networkmap/zigbee2mqtt-networkmap.js
      type: module
    - url: /local/community/vacuum-card/vacuum-card.js
      type: module
    - url: /local/community/lovelace-xiaomi-vacuum-map-card/xiaomi-vacuum-map-card.js
      type: module
    - url: /local/community/transmission-card/transmission-card.js
      type: module
    - url: /local/community/flex-table-card/flex-table-card.js
      type: module
    - url: /local/community/LG-WebOS-Remote-Control/lg-remote-control.js
      type: module
    - url: /local/community/mini-media-player/mini-media-player-bundle.js
      type: module
