title: Maison Seonyu
views:
  - !include lovelaces/views/home.yaml
  - !include lovelaces/views/air_conditioner.yaml
  - !include lovelaces/views/robot_vacuum.yaml
  - !include lovelaces/views/media.yaml
  - !include lovelaces/views/tesla.yaml
  - !include lovelaces/views/monitoring.yaml
  - !include lovelaces/views/zigbee_network_map.yaml
  - !include lovelaces/views/dev.yaml

button_card_templates: !include lovelaces/templates/button_card.yaml
