# Input select for Zigbee2MQTT debug level
input_select:
  zigbee2mqtt_log_level:
    name: Zigbee2MQTT Log Level
    options:
      - debug
      - info
      - warn
      - error
    initial: info
    icon: mdi:format-list-bulleted

# Input number for joining time remaining (in minutes)
input_number:
  zigbee2mqtt_join_minutes:
    name: "Zigbee2MQTT join minutes"
    initial: 2
    min: 1
    max: 5
    step: 1
    mode: slider

# Input text to input Zigbee2MQTT friendly_name for scripts
input_text:
  zigbee2mqtt_old_name:
    name: Zigbee2MQTT Old Name
    initial: ""
  zigbee2mqtt_new_name:
    name: Zigbee2MQTT New Name
    initial: ""
  zigbee2mqtt_remove:
    name: Zigbee2MQTT Remove
    initial: ""

# Input boolean to set the force remove flag for devices
input_boolean:
  zigbee2mqtt_force_remove:
    name: Zigbee2MQTT Force Remove
    initial: false
    icon: mdi:alert-remove

# Scripts for renaming & removing devices
script:
  zigbee2mqtt_rename:
    alias: Zigbee2MQTT Rename
    sequence:
      service: mqtt.publish
      data_template:
        topic: zigbee2mqtt/bridge/request/device/rename
        payload_template: >-
          {
            "from": "{{ states.input_text.zigbee2mqtt_old_name.state | string }}",
            "to": "{{ states.input_text.zigbee2mqtt_new_name.state | string }}"
          }
  zigbee2mqtt_remove:
    alias: Zigbee2MQTT Remove
    sequence:
      service: mqtt.publish
      data_template:
        topic: zigbee2mqtt/bridge/request/device/remove
        payload_template: >-
          { 
            "id": "{{ states.input_text.zigbee2mqtt_remove.state | string }}", 
            "force": {% if states.input_boolean.zigbee2mqtt_force_remove.state == "off" %}false{% else %}true{% endif %}
          }

# Timer for joining time remaining (120 sec = 2 min)
timer:
  zigbee_permit_join:
    name: Time remaining
    duration: 120

sensor:
  # Sensor for monitoring the bridge state
  - platform: mqtt
    name: Zigbee2MQTT Bridge state
    state_topic: "zigbee2mqtt/bridge/state"
    icon: mdi:router-wireless
  # Sensor for Showing the Zigbee2MQTT Version
  - platform: mqtt
    name: Zigbee2MQTT Version
    state_topic: "zigbee2mqtt/bridge/config"
    value_template: "{{ value_json.version }}"
    icon: mdi:zigbee
  # Sensor for Showing the Coordinator Version
  - platform: mqtt
    name: Coordinator Version
    state_topic: "zigbee2mqtt/bridge/config"
    value_template: "{{ value_json.coordinator }}"
    icon: mdi:chip
  # Sensor for z2m network map (hacs)
  - platform: mqtt
    name: Zigbee2mqtt Networkmap
    # if you change base_topic of Zigbee2mqtt, change state_topic accordingly
    state_topic: zigbee2mqtt/bridge/networkmap/raw
    value_template: >-
      {{ now().strftime('%Y-%m-%d %H:%M:%S') }}
    # again, if you change base_topic of Zigbee2mqtt, change json_attributes_topic accordingly
    json_attributes_topic: zigbee2mqtt/bridge/networkmap/raw

# Switch for enabling joining
switch:
  - platform: mqtt
    name: "Zigbee2MQTT Main join"
    state_topic: "zigbee2mqtt/bridge/info"
    value_template: "{{ value_json.permit_join | lower }}"
    command_topic: "zigbee2mqtt/bridge/request/permit_join"
    payload_on: "true"
    payload_off: "false"

automation:
  # Automation for sending MQTT message on input select change
  - alias: Zigbee2MQTT Log Level
    initial_state: "on"
    trigger:
      platform: state
      entity_id: input_select.zigbee2mqtt_log_level
    action:
      - service: mqtt.publish
        data:
          payload_template: "{{ states('input_select.zigbee2mqtt_log_level') }}"
          topic: zigbee2mqtt/bridge/request/config/log_level
  # Automation to start timer when enable join is turned on
  - id: zigbee_join_enabled
    alias: Zigbee Join Enabled
    trigger:
      platform: state
      entity_id: switch.zigbee2mqtt_main_join
      to: "on"
    action:
      service: timer.start
      entity_id: timer.zigbee_permit_join
      data_template:
        duration: "{{ '00:0%i:00' % (states('input_number.zigbee2mqtt_join_minutes') | int ) }}"
  # Automation to stop timer when switch turned off and turn off switch when timer finished
  - id: zigbee_join_disabled
    alias: Zigbee Join Disabled
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.zigbee_permit_join
      - platform: state
        entity_id: switch.zigbee2mqtt_main_join
        to: "off"
    action:
      - service: timer.cancel
        data:
          entity_id: timer.zigbee_permit_join
      - service: switch.turn_off
        entity_id: switch.zigbee2mqtt_main_join
  - id: "zigbee2mqtt_create_notification_on_successfull_interview"
    alias: Zigbee Device Joined Notification
    trigger:
      platform: mqtt
      topic: "zigbee2mqtt/bridge/event"
    condition:
      condition: template
      value_template: '{{trigger.payload_json.type == "device_interview" and trigger.payload_json.data.status == "successful" and trigger.payload_json.data.supported}}'
    action:
      - service: persistent_notification.create
        data_template:
          title: Device joined the Zigbee2MQTT network
          message: "Name: {{trigger.payload_json.data.friendly_name}},
            Vendor: {{trigger.payload_json.data.definition.vendor}},
            Model: {{trigger.payload_json.data.definition.model}},
            Description: {{trigger.payload_json.data.definition.description}}"
  # alert callback: https://www.home-assistant.io/integrations/alert/
  - alias: "Telegram callback to stop alerts for door"
    trigger:
      - platform: event
        event_type: telegram_callback
        event_data:
          data: "/door_acknowledge"
    condition:
      - condition: state
        entity_id: alert.smartthings_door_contact_contact
        state: "on"
    action:
      - service: alert.turn_off
        target:
          entity_id: alert.smartthings_door_contact_contact

# binary sensors for alert integration
binary_sensor:
  - platform: template
    sensors:
      hue_bedroom_motion_battery_low:
        value_template: "{{ state_attr('sensor.hue_bedroom_motion_battery', 'battery') < 15 }}"
  - platform: template
    sensors:
      hej_bathroom_thsensor_battery_low:
        value_template: "{{ state_attr('sensor.hej_bathroom_thsensor_battery', 'battery') < 15 }}"
  - platform: template
    sensors:
      hej_bedroom_thsensor_battery_low:
        value_template: "{{ state_attr('sensor.hej_bedroom_thsensor_battery', 'battery') < 15 }}"
  - platform: template
    sensors:
      hej_laundryroom_thsensor_battery_low:
        value_template: "{{ state_attr('sensor.hej_laundryroom_thsensor_battery', 'battery') < 15 }}"

# alert: https://www.home-assistant.io/integrations/alert/
alert:
  # battery is low
  smartthings_door_contact_battery_low:
    name: Door Contact Battery is Low
    message: Door Contact Battery is low
    done_message: Door Contact Battery is fine
    entity_id: binary_sensor.smartthings_door_contact_battery_low
    repeat: 360
    notifiers:
      - notify_telegram
  smartthings_library_contact_battery_low:
    name: Library Contact Battery is Low
    message: Library Contact Battery is low
    done_message: Library Contact Battery is fine
    entity_id: binary_sensor.smartthings_library_contact_battery_low
    repeat: 360
    notifiers:
      - notify_telegram
  smartthings_dressroom_contact_battery_low:
    name: Dressroom Contact Battery is Low
    message: Dressroom Contact Battery is low
    done_message: Dressroom Contact Battery is fine
    entity_id: binary_sensor.smartthings_dressroom_contact_battery_low
    repeat: 360
    notifiers:
      - notify_telegram
  smartthings_bedroom_contact_battery_low:
    name: Bedroom Contact Battery is Low
    message: Bedroom Contact Battery is low
    done_message: Bedroom Contact Battery is fine
    entity_id: binary_sensor.smartthings_bedroom_contact_battery_low
    repeat: 360
    notifiers:
      - notify_telegram
  smartthings_laundryroom_contact_battery_low:
    name: Laundryroom Contact Battery is Low
    message: Laundryroom Contact Battery is low
    done_message: Laundryroom Contact Battery is fine
    entity_id: binary_sensor.smartthings_laundryroom_contact_battery_low
    repeat: 360
    notifiers:
      - notify_telegram
  smartthings_bathroom_contact_battery_low:
    name: Bathroom Contact Battery is Low
    message: Bathroom Contact Battery is low
    done_message: Bathroom Contact Battery is fine
    entity_id: binary_sensor.smartthings_bathroom_contact_battery_low
    repeat: 360
    notifiers:
      - notify_telegram
  smartthings_library_motion_battery_low:
    name: Library Motion Battery is Low
    message: Library Motion Battery is low
    done_message: Library Motion Battery is fine
    entity_id: binary_sensor.smartthings_library_motion_battery_low
    repeat: 360
    notifiers:
      - notify_telegram
  smartthings_dressroom_motion_battery_low:
    name: Dressroom Motion Battery is Low
    message: Dressroom Motion Battery is low
    done_message: Dressroom Motion Battery is fine
    entity_id: binary_sensor.smartthings_dressroom_motion_battery_low
    repeat: 360
    notifiers:
      - notify_telegram
  smartthings_kitchen_motion_battery_low:
    name: Kitchen Motion Battery is Low
    message: Kitchen Motion Battery is low
    done_message: Kitchen Motion Battery is fine
    entity_id: binary_sensor.smartthings_kitchen_motion_battery_low
    repeat: 360
    notifiers:
      - notify_telegram
  smartthings_bathroom_motion_battery_low:
    name: Bathroom Motion Battery is Low
    message: Bathroom Motion Battery is low
    done_message: Bathroom Motion Battery is fine
    entity_id: binary_sensor.smartthings_bathroom_motion_battery_low
    repeat: 360
    notifiers:
      - notify_telegram
  smartthings_laundryroom_motion_battery_low:
    name: Laundryroom Motion Battery is Low
    message: Laundryroom Motion Battery is low
    done_message: Laundryroom Motion Battery is fine
    entity_id: binary_sensor.smartthings_laundryroom_motion_battery_low
    repeat: 360
    notifiers:
      - notify_telegram
  hue_bedroom_motion_battery_low:
    name: Bedroom Motion Battery is Low
    message: Bedroom Motion Battery is low
    done_message: Bedroom Motion Battery is fine
    entity_id: binary_sensor.hue_bedroom_motion_battery_low
    repeat: 360
    notifiers:
      - notify_telegram
  blitzwolf_bathroom_ceiling_waterleak_battery_low:
    name: Bathroom Ceiling Waterleak Battery is Low
    message: Bathroom Ceilng Waterleak Battery is low
    done_message: Bathroom Ceilng Waterleak Battery is fine
    entity_id: binary_sensor.blitzwolf_bathroom_ceiling_waterleak_battery_low
    repeat: 360
    notifiers:
      - notify_telegram
  blitzwolf_bathroom_sink_waterleak_battery_low:
    name: Bathroom Sink Waterleak Battery is Low
    message: Bathroom Sink Waterleak Battery is low
    done_message: Bathroom Sink Waterleak Battery is fine
    entity_id: binary_sensor.blitzwolf_bathroom_sink_waterleak_battery_low
    repeat: 360
    notifiers:
      - notify_telegram
  blitzwolf_kitchen_boiler_waterleak_battery_low:
    name: Kitchen Boiler Waterleak Battery is Low
    message: Kitchen Boiler Waterleak Battery is low
    done_message: Kitchen Boiler Waterleak Battery is fine
    entity_id: binary_sensor.blitzwolf_kitchen_boiler_waterleak_battery_low
    repeat: 360
    notifiers:
      - notify_telegram
  blitzwolf_kitchen_sink_waterleak_battery_low:
    name: Kitchen Sink Waterleak Battery is Low
    message: Kitchen Sink Waterleak Battery is low
    done_message: Kitchen Sink Waterleak Battery is fine
    entity_id: binary_sensor.blitzwolf_kitchen_sink_waterleak_battery_low
    repeat: 360
    notifiers:
      - notify_telegram
  blitzwolf_laundryroom_waterleak_battery_low:
    name: Laundryroom Waterleak Battery is Low
    message: Laundryroom Waterleak Battery is low
    done_message: Laundryroom Waterleak Battery is fine
    entity_id: binary_sensor.blitzwolf_laundryroom_waterleak_battery_low
    repeat: 360
    notifiers:
      - notify_telegram
  hej_bathroom_thsensor_battery_low:
    name: Bathroom Temperature Humidity Sensor Battery is Low
    message: Bathroom Temperature Humidity Sensor Battery is low
    done_message: Bathroom Temperature Humidity Sensor  Battery is fine
    entity_id: binary_sensor.hej_bathroom_thsensor_battery_low
    repeat: 360
    notifiers:
      - notify_telegram
  hej_bedroom_thsensor_battery_low:
    name: Bedroom Temperature Humidity Sensor Battery is Low
    message: Bedroom Temperature Humidity Sensor Battery is low
    done_message: Bedroom Temperature Humidity Sensor  Battery is fine
    entity_id: binary_sensor.hej_bedroom_thsensor_battery_low
    repeat: 360
    notifiers:
      - notify_telegram
  hej_laundryroom_thsensor_battery_low:
    name: Laundryroom Temperature Humidity Sensor Battery is Low
    message: Laundryroom Temperature Humidity Sensor Battery is low
    done_message: Laundryroom Temperature Humidity Sensor  Battery is fine
    entity_id: binary_sensor.hej_laundryroom_thsensor_battery_low
    repeat: 360
    notifiers:
      - notify_telegram
  # water leaked
  blitzwolf_bathroom_ceiling_waterleak_water_leak:
    name: Bathroom Ceiling Waterleak Leaked
    message: Water is leaking from bathroom ceiling
    done_message: Water leak is stopped
    entity_id: binary_sensor.blitzwolf_bathroom_ceiling_waterleak_water_leak
    repeat:
      - 1
      - 3
      - 15
    notifiers:
      - notify_telegram
  blitzwolf_bathroom_sink_waterleak_water_leak:
    name: Bathroom Sink Waterleak Leaked
    message: Water is leaking from bathroom sink
    done_message: Water leak is stopped
    entity_id: binary_sensor.blitzwolf_bathroom_sink_waterleak_water_leak
    repeat:
      - 1
      - 3
      - 15
    notifiers:
      - notify_telegram
  blitzwolf_kitchen_boiler_waterleak_water_leak:
    name: Kitchen Boiler Waterleak Leaked
    message: Water is leaking from kitchen boiler
    done_message: Water leak is stopped
    entity_id: binary_sensor.blitzwolf_kitchen_boiler_waterleak_water_leak
    repeat:
      - 1
      - 3
      - 15
    notifiers:
      - notify_telegram
  blitzwolf_kitchen_sink_waterleak_water_leak:
    name: Kitchen Sink Waterleak Leaked
    message: Water is leaking from kitchen sink
    done_message: Water leak is stopped
    entity_id: binary_sensor.blitzwolf_kitchen_sink_waterleak_water_leak
    repeat:
      - 1
      - 3
      - 15
    notifiers:
      - notify_telegram
  blitzwolf_laundryroom_waterleak_water_leak:
    name: Laundryroom Waterleak Leaked
    message: Water is leaking from laundryroom
    done_message: Water leak is stopped
    entity_id: binary_sensor.blitzwolf_laundryroom_waterleak_water_leak
    repeat:
      - 1
      - 3
      - 15
    notifiers:
      - notify_telegram
  # door open
  smartthings_door_contact_contact:
    name: Door is open
    message: Door is still open
    done_message: Door is closed
    entity_id: binary_sensor.smartthings_door_contact_contact
    skip_first: true
    repeat:
      - 1
      - 3
      - 15
    data:
      inline_keyboard:
        - "Acknowledge:/door_acknowledge"
    notifiers:
      - notify_telegram
