# kitchen

input_boolean:
  food_waste_machine_state:
    name: Food waste machine state
    initial: false
  dish_washer_state:
    name: Dish washer state
    initial: false
  co2_unhealthy_state:
    name: CO2 unhealthy state
    initial: false

automation:
  - alias: "CO2 level has reached unhealty state"
    trigger:
      - platform: numeric_state
        entity_id: sensor.samseong_eeomoniteo_carbon_dioxide_measurement
        for: "00:10:00"
        above: 1400
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.co2_unhealthy_state
      - service: notify.notify_telegram
        data:
          title: Unhealthy CO2 level
          message: Please open the windows.
      - condition: state
        entity_id: alarm_control_panel.home_monitoring
        state: "disarmed"
      - service: notify.in_the_kitchen
        data:
          message: "이산화탄소 수치가 높습니다. 창문을 열어 환기해 주세요."
  - alias: "CO2 level has come back to normal"
    trigger:
      - platform: numeric_state
        entity_id: sensor.samseong_eeomoniteo_carbon_dioxide_measurement
        for: "00:03:00"
        below: 1000
    condition:
      - condition: state
        entity_id: input_boolean.co2_unhealthy_state
        state: "on"
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.co2_unhealthy_state
      - service: notify.notify_telegram
        data:
          title: Normal CO2 level
          message: Please close the windows.
      - condition: state
        entity_id: alarm_control_panel.home_monitoring
        state: "disarmed"
      - service: notify.in_the_kitchen
        data:
          message: "이산화탄소 수치가 정상으로 돌아왔습니다."
